== Name

msh - A ruby shell

== Synopsis

**msh** [-V,--version] [-h,--help] [-c command] [--] [program_file]...

== Description

**msh** is a bash/sh-like language implemented in Ruby.

== Features

**Interpolation**::
  Use `#{}` to interpolate Ruby code anywhere.

**Interpreter**::
  Access the current Ruby interpreter using `#{self}`, or via an
  interactive REPL, all on that same instance.

**Methods / Functions**::
  The `alias -> function -> exe` lookup of **sh** is now
  `alias -> method -> exe`, which means functions are just
  _methods_ on our `#{self}`.

**Portability**::
  The primary implementation targets MRuby, in order to be distributed
  as a _single_ binary executable.

=== Example

```
<%= MshMainManpageExample.new.run %>
```

== Documentation

msh intends to be self-documenting via manpages, similar to git(1).

```
msh help [topic]
man msh-<topic>
```

For info on where to go from here, or a list of the available topics,
see msh-help(1).

== Development

Source code, issue tracker, and releases can be found at
https://github.com/jethrodaniel/msh.

To clone, build, install, and test

```
git clone --recursive https://github.com/jethrodaniel/msh
cd msh
bundle
bundle exec rake
```

== Alternatives

- https://elv.sh/
- https://github.com/ChrisPritchard/FSH
- https://github.com/PowerShell/PowerShell
- https://github.com/bminor/bash
- https://github.com/dundalek/closh
- https://github.com/fish-shell/fish-shell
- https://github.com/nushell/nushell
- https://github.com/zsh-users/zsh

== Copyright

<%= File.read("license.txt") %>
