inherit_from:
  - https://raw.githubusercontent.com/jethrodaniel/dotfiles/master/home/.config/rubocop/config.yml

Style/SpecialGlobalVars:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/msh*/**/*_spec.rb'

Security/Eval:
  Exclude:
    - 'spec/msh/*_spec.rb'
