inherit_from:
  - https://raw.githubusercontent.com/jethrodaniel/dotfiles/master/home/.config/rubocop/config.yml

AllCops:
  TargetRubyVersion: 2.5

Security/Eval:
  Exclude:
    - 'spec/msh/lexer_spec.rb'
    - 'spec/msh/parser_spec.rb'
    - 'spec/msh/interpreter_spec.rb'
