inherit_from:
  - https://raw.githubusercontent.com/jethrodaniel/dotfiles/master/home/.config/rubocop/config.yml

AllCops:
  Excluded:
    - 'bin/console'

Style/SpecialGlobalVars:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/msh*/**/*_spec.rb'

Security/Eval:
  Exclude:
    - 'spec/msh/*_spec.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'spec/msh*/**/*_spec.rb'

Style/RedundantPercentQ:
  Exclude:
    - 'spec/msh*/**/*_spec.rb'

