'\" t
.\"     Title: msh-history
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-05-22
.\"    Manual: Msh Manual
.\"    Source: Msh v0.1.0
.\"  Language: English
.\"
.TH "HISTORY" "1" "2020-05-22" "Msh v0.1.0" "Msh Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
history \- shell history
.SH "SYNOPSIS"
.sp
\fBhistory\fP
.sp
\fBhist\fP
.SH "DESCRIPTION"
.sp
Shows shell history with line numbers.
.SH "MSH"
.sp
Part of msh(1).