'\" t
.\"     Title: msh-parser
.\"    Author: Copyright 2020, Mark Delk under the terms of the MIT license
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-03-21
.\"    Manual: Msh Manual
.\"    Source: Msh v0.1.0
.\"  Language: English
.\"
.TH "PARSER" "1" "2020-03-21" "Msh v0.1.0" "Msh Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
parser \- msh\(aqs parser
.SH "SYNOPSIS"
.sp
\fBparser\fP [\fIfile\fP]...
.SH "DESCRIPTION"
.sp
Run the parser.
.SH "MSH"
.sp
Part of msh(1).
.SH "AUTHOR"
.sp
Copyright 2020, Mark Delk under the terms of the MIT license