'\" t
.\"     Title: msh-repl
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-06-04
.\"    Manual: Msh Manual
.\"    Source: Msh v0.2.0
.\"  Language: English
.\"
.TH "REPL" "1" "2020-06-04" "Msh v0.2.0" "Msh Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
repl \- easily access Msh\(aqs Ruby interpretor
.SH "SYNOPSIS"
.sp
\fBrepl\fP
.SH "DESCRIPTION"
.sp
This is equivalent to
.sp
.if n .RS 4
.nf
#{binding.irb}  # if using IRB
#{binding.pry}  # if using Pry
.fi
.if n .RE
.SH "MSH"
.sp
Part of msh(1).