'\" t
.\"     Title: msh-help
.\"    Author: Copyright 2020, Mark Delk under the terms of the MIT license
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-03-15
.\"    Manual: Msh Manual
.\"    Source: Msh v0.1.0
.\"  Language: English
.\"
.TH "HELP" "1" "2020-03-15" "Msh v0.1.0" "Msh Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
help \- msh man pages
.SH "SYNOPSIS"
.sp
\fBhelp\fP [\fItopic\fP]...
.SH "DESCRIPTION"
.sp
Msh\(cqs \fIhelp\fP builtin is just a wrapper around the \fIman\fP command, such that topics are prefixed with \fImsh\-\fP.
.sp
.if n .RS 4
.nf
msh> help help   #=> same as `man msh\-help`
msh> help        #=> same as `man msh`
msh> help wtf    #=> No manual entry for msh\-wtf
.fi
.if n .RE
.sp
Msh modifies your $MANPATH so these are available. To install them outside of msh, either add msh\(cqs man directory to your $MANPATH, or install it\(cqs manpages on your system the traditional way.
.sp
.if n .RS 4
.nf
MANPATH="$MANPATH:`dirname \(rs`gem which msh\(rs``/../man" man msh
.fi
.if n .RE
.sp
.if n .RS 4
.nf
cp \-r `dirname \(rs`gem which msh\(rs``/../man/man1/ /usr/local/share/man/man1/
mandb
man msh
.fi
.if n .RE
.SH "MSH"
.sp
Part of msh(1).
.SH "AUTHOR"
.sp
Copyright 2020, Mark Delk under the terms of the MIT license