name: ci

on: [push]

jobs:
  mruby:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: apt dependencies
      run: sudo apt install -y gperf bison gcc g++

    - name: set up ruby for building
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: setup bundler, gems for building
      run: |
        gem install bundler
        bundle update --bundler
        bundle install

    - name: do it
      run: |
        make

  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5.x', '2.6.x', '2.7.x']
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: setup bundler, gems
      run: |
        gem install bundler
        bundle update --bundler
        bundle install

    # - name: Setup tmate session
      # uses: mxschmitt/action-tmate@v2

    - name: run specs
      run: |
        # These specs require a tty.
        #
        # See https://stackoverflow.com/a/32981392/7132678
        #
        faketty() { script -qfec "$(printf "%q " "$@")"; }; faketty bundle exec rake spec
