# from https://raw.githubusercontent.com/Blacksmoke16/oq/1e7c6570fcbf0de9346241b55f7c357a1550d515/.github/workflows/deployment.yml

name: release binaries

on:
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: apt dependencies
      run: sudo apt install -y gperf bison gcc g++   curl rpm debsigs

    - name: set up ruby for building
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: setup bundler, gems for building
      run: |
        gem install bundler
        bundle update --bundler
        bundle install

    - name: build
      run: |
        bundle exec rake pkg:all

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'pkg/*msh*'
